document.getElementById("leadForm")
.addEventListener("submit", function(e){

e.preventDefault();

const name = document.getElementById("name").value;
const email = document.getElementById("email").value;

fetch("https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec", {
method: "POST",
body: JSON.stringify({
name: name,
email: email
})
})
.then(res => res.text())
.then(data => {

window.location.href = "thankyou.html";

});

});
